version: '3.8'

services:
  node-app:
    build: .
    container_name: weather-node-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      MONGO_URI: mongodb://mongodb:27017/miapp
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/app

  mongodb:
    image: mongo:4.4
    container_name: weather-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  redis:
    image: redis:alpine
    container_name: weather-redis
    ports:
      - "6379:6379"
